server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yc?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: mgg
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: select 1
  redis:
    port: 6379
    host: 47.105.230.85
    password: 135790
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.yzm.majorserver: info
    org.springfromework.web: info
imgDirPath: /Users/yizuomin/major-repository/major-vue/static/images/headerImg/